# recipe/meta.yaml
package:
  name: sdrf-pipelines
  version: "1.0.0"

source:
  path: ../

build:
  noarch: python
  entry_points:
      - parse_sdrf = sdrf_pipelines.parse_sdrf:main
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed .[all]

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >=3.10
    - click
    - defusedxml
    - numpy
    - pandas
    - pydantic >=2.0.0
    - pyyaml
    # Optional ontology dependencies
    - fastparquet
    - pooch
    - rdflib
    - requests

test:
  imports:
    - sdrf_pipelines
    - sdrf_pipelines.converters
    - sdrf_pipelines.converters.openms
    - sdrf_pipelines.converters.maxquant
    - sdrf_pipelines.converters.msstats
    - sdrf_pipelines.converters.normalyzerde
    - sdrf_pipelines.sdrf
    - sdrf_pipelines.utils
    - sdrf_pipelines.ols
  commands:
    - parse_sdrf --help

about:
  home: "https://github.com/bigbio/sdrf-pipelines"
  license: Apache 2
  ##license_file: LICENSE ## patch is applied upstream, next version will have it
  summary: "Translate, convert SDRF to configuration pipelines"
  doc_url: "https://github.com/bigbio/sdrf-pipelines"
  dev_url: "https://github.com/bigbio/sdrf-pipelines"
