"""Constants for the MHCquant SDRF converter."""

# Column alias pairs: (new_name, old_name)
# Check new names first, fall back to old names
COLUMN_ALIASES = {
    "comment[ms min mz]": "comment[precursor min mz]",
    "comment[ms max mz]": "comment[precursor max mz]",
    "comment[ms min charge]": "comment[precursor min charge]",
    "comment[ms max charge]": "comment[precursor max charge]",
    "comment[ms min rt]": "comment[min retention time]",
    "comment[ms max rt]": "comment[max retention time]",
    "comment[ms min im]": "comment[min ion mobility]",
    "comment[ms max im]": "comment[max ion mobility]",
}

# Fields required to build a complete custom preset (all must be present)
REQUIRED_PRESET_FIELDS = [
    "precursor_mass_tolerance",
    "precursor_error_unit",
    "fragment_mass_tolerance",
    "precursor_mass_range",
    "precursor_charge",
    "activation_method",
    "instrument_resolution",
    "mhc_class",
]

# MHC class → (min_peptide_length, max_peptide_length)
MHC_CLASS_PEPTIDE_LENGTHS = {
    "class1": (8, 14),
    "class2": (8, 30),
}

# Instrument name patterns → preset prefix
# Keys are lowercased patterns to match against the instrument name
INSTRUMENT_PRESET_MAP = [
    # Order matters: more specific patterns first
    (["lumos", "fusion", "exploris", "eclipse"], "lumos"),
    (["q exactive", "exactive"], "qe"),
    (["timstof", "tims tof"], "timstof"),
    (["astral"], "astral"),
    (["ltq orbitrap xl", "orbitrap xl"], "xl"),
]

# 10 built-in default presets from nf-core/mhcquant assets/search_presets.tsv
DEFAULT_PRESETS = {
    "lumos_class1": {
        "PresetName": "lumos_class1",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 14,
        "PrecursorMassRange": "800:2500",
        "PrecursorCharge": "2:3",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "Immuno-HCD",
        "ActivationMethod": "HCD",
        "Instrument": "high_res",
        "NumberMods": 3,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "lumos_class2": {
        "PresetName": "lumos_class2",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 30,
        "PrecursorMassRange": "800:5000",
        "PrecursorCharge": "2:5",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "Immuno-HCD",
        "ActivationMethod": "HCD",
        "Instrument": "high_res",
        "NumberMods": 5,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "qe_class1": {
        "PresetName": "qe_class1",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 14,
        "PrecursorMassRange": "800:2500",
        "PrecursorCharge": "2:3",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "Immuno-HCD",
        "ActivationMethod": "HCD",
        "Instrument": "high_res",
        "NumberMods": 3,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "qe_class2": {
        "PresetName": "qe_class2",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 30,
        "PrecursorMassRange": "800:5000",
        "PrecursorCharge": "2:5",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "Immuno-HCD",
        "ActivationMethod": "HCD",
        "Instrument": "high_res",
        "NumberMods": 5,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "timstof_class1": {
        "PresetName": "timstof_class1",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 14,
        "PrecursorMassRange": "800:2500",
        "PrecursorCharge": "1:4",
        "PrecursorMassTolerance": 20,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "timsTOF",
        "ActivationMethod": "CID",
        "Instrument": "high_res",
        "NumberMods": 3,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "timstof_class2": {
        "PresetName": "timstof_class2",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 30,
        "PrecursorMassRange": "800:5000",
        "PrecursorCharge": "1:5",
        "PrecursorMassTolerance": 20,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "timsTOF",
        "ActivationMethod": "CID",
        "Instrument": "high_res",
        "NumberMods": 5,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "astral_class1": {
        "PresetName": "astral_class1",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 14,
        "PrecursorMassRange": "800:2500",
        "PrecursorCharge": "2:3",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "Immuno-HCD",
        "ActivationMethod": "HCD",
        "Instrument": "high_res",
        "NumberMods": 3,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "astral_class2": {
        "PresetName": "astral_class2",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 30,
        "PrecursorMassRange": "800:5000",
        "PrecursorCharge": "2:5",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.01,
        "FragmentBinOffset": 0.0,
        "MS2PIPModel": "Immuno-HCD",
        "ActivationMethod": "HCD",
        "Instrument": "high_res",
        "NumberMods": 5,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "xl_class1": {
        "PresetName": "xl_class1",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 14,
        "PrecursorMassRange": "800:2500",
        "PrecursorCharge": "2:3",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.50025,
        "FragmentBinOffset": 0.4,
        "MS2PIPModel": "CIDch2",
        "ActivationMethod": "CID",
        "Instrument": "low_res",
        "NumberMods": 3,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
    "xl_class2": {
        "PresetName": "xl_class2",
        "PeptideMinLength": 8,
        "PeptideMaxLength": 30,
        "PrecursorMassRange": "800:5000",
        "PrecursorCharge": "2:5",
        "PrecursorMassTolerance": 5,
        "PrecursorErrorUnit": "ppm",
        "FragmentMassTolerance": 0.50025,
        "FragmentBinOffset": 0.4,
        "MS2PIPModel": "CIDch2",
        "ActivationMethod": "CID",
        "Instrument": "low_res",
        "NumberMods": 5,
        "FixedMods": "",
        "VariableMods": "Oxidation (M)",
    },
}

# Preset column order for output TSV
PRESET_COLUMNS = [
    "PresetName",
    "PeptideMinLength",
    "PeptideMaxLength",
    "PrecursorMassRange",
    "PrecursorCharge",
    "PrecursorMassTolerance",
    "PrecursorErrorUnit",
    "FragmentMassTolerance",
    "FragmentBinOffset",
    "MS2PIPModel",
    "ActivationMethod",
    "Instrument",
    "NumberMods",
    "FixedMods",
    "VariableMods",
]
