name: default
description: Default SDRF template with common fields
validators:
 - type: min_columns
   params:
     min: 7
 - type: whitespace
   params: {}
fields:
- name: source_name
  sdrf_name: source name
  description: Source name
  requirement: required
- name: characteristics_organism
  sdrf_name: characteristics[organism]
  description: Organism
  requirement: required
  validators:
  - type: ontology
    params:
      ontology_name: ncbitaxon
      allow_not_applicable: true
      allow_not_available: false
      description: The organism should be a valid NCBI Taxonomy term
      examples:
      - homo sapiens
      - mus musculus
      - rattus norvegicus
- name: characteristics_organism_part
  sdrf_name: characteristics[organism part]
  description: Organism part
  requirement: required
- name: characteristics_disease
  sdrf_name: characteristics[disease]
  description: Disease
  requirement: required
- name: characteristics_cell_type
  sdrf_name: characteristics[cell type]
  description: Cell type
  requirement: required
  validators:
  - type: ontology
    params:
      ontologies:
      - cl
      - bto
      - clo
      allow_not_applicable: true
      allow_not_available: true
      description: The cell type should be a valid Cell Ontology (CL), BRENDA Tissue
        Ontology (BTO), or Cell Line Ontology (CLO) term
      examples:
      - hepatocyte
      - neuron
      - fibroblast
- name: characteristics_biological_replicate
  sdrf_name: characteristics[biological replicate]
  description: Biological replicate
  requirement: required
- name: assay_name
  sdrf_name: assay name
  description: Assay name
  requirement: required
- name: technology_type
  sdrf_name: technology type
  description: Technology type
  requirement: required
- name: comment_technical_replicate
  sdrf_name: comment[technical replicate]
  description: Technical replicate
  requirement: required
- name: comment_fraction_identifier
  sdrf_name: comment[fraction identifier]
  description: Fraction identifier
  requirement: required
- name: comment_label
  sdrf_name: comment[label]
  description: Label
  requirement: required
  validators:
  - type: ontology
    params:
      ontology_name: pride
      allow_not_applicable: false
      allow_not_available: false
      description: The label should be a valid PRIDE ontology term
      examples:
      - label free sample
      - SILAC light
      - SILAC heavy
      - TMT126
      - iTRAQ114
- name: comment_data_file
  sdrf_name: comment[data file]
  description: Data file
  requirement: required
- name: comment_instrument
  sdrf_name: comment[instrument]
  description: Instrument
  requirement: required
  validators:
  - type: ontology
    params:
      ontology_name: ms
      allow_not_applicable: false
      allow_not_available: false
      description: The instrument should be a valid MS ontology term
      examples:
      - LTQ Orbitrap
      - Q Exactive
      - TripleTOF 5600
      - Orbitrap Fusion Lumos
- name: comment_modification_parameters
  sdrf_name: comment[modification parameters]
  description: Modification parameters
  requirement: recommended
  validators:
  - type: ontology
    params:
      ontology_name: unimod
      allow_not_applicable: false
      allow_not_available: true
      description: The modification parameters should be valid Unimod terms
      examples:
      - "NT=Oxidation;MT=Variable;TA=M;AC=Unimod:35"
      - "NT=Carbamidomethyl;TA=C;MT=fixed;AC=UNIMOD:4"
- name: comment_cleavage_agent_details
  sdrf_name: comment[cleavage agent details]
  description: Cleavage agent details
  requirement: optional
  validators:
  - type: ontology
    params:
      ontology_name: ms
      allow_not_applicable: true
      allow_not_available: false
      description: The cleavage agent details should be valid MS ontology terms
      examples:
      - Trypsin
      - Lys-C
      - Arg-C
      - Chymotrypsin
- name: comment_fragment_mass_tolerance
  sdrf_name: comment[fragment mass tolerance]
  description: Fragment mass tolerance
  requirement: optional
- name: comment_precursor_mass_tolerance
  sdrf_name: comment[precursor mass tolerance]
  description: Precursor mass tolerance
  requirement: optional