"""Constants for OpenMS conversion including label plexes and enzyme mappings."""

# Canonical 1-based OpenMS channel ordinal -> SDRF/QPX label. These labels are
# join keys, so their spelling and capitalization are part of the public API.
_CHANNEL_LABELS: dict[str, tuple[str, ...]] = {
    "tmt6plex": ("TMT126", "TMT127", "TMT128", "TMT129", "TMT130", "TMT131"),
    "tmt10plex": (
        "TMT126",
        "TMT127N",
        "TMT127C",
        "TMT128N",
        "TMT128C",
        "TMT129N",
        "TMT129C",
        "TMT130N",
        "TMT130C",
        "TMT131",
    ),
    "tmt11plex": (
        "TMT126",
        "TMT127N",
        "TMT127C",
        "TMT128N",
        "TMT128C",
        "TMT129N",
        "TMT129C",
        "TMT130N",
        "TMT130C",
        "TMT131N",
        "TMT131C",
    ),
    "tmt16plex": (
        "TMT126",
        "TMT127N",
        "TMT127C",
        "TMT128N",
        "TMT128C",
        "TMT129N",
        "TMT129C",
        "TMT130N",
        "TMT130C",
        "TMT131N",
        "TMT131C",
        "TMT132N",
        "TMT132C",
        "TMT133N",
        "TMT133C",
        "TMT134N",
    ),
    "tmt18plex": (
        "TMT126",
        "TMT127N",
        "TMT127C",
        "TMT128N",
        "TMT128C",
        "TMT129N",
        "TMT129C",
        "TMT130N",
        "TMT130C",
        "TMT131N",
        "TMT131C",
        "TMT132N",
        "TMT132C",
        "TMT133N",
        "TMT133C",
        "TMT134N",
        "TMT134C",
        "TMT135N",
    ),
    # High-plex ordinals follow OpenMS's mass-interleaved channel_names_ order.
    "tmt32plex": (
        "TMT126",
        "TMT127N",
        "TMT127C",
        "TMT127D",
        "TMT128N",
        "TMT128C",
        "TMT128ND",
        "TMT128CD",
        "TMT129N",
        "TMT129C",
        "TMT129ND",
        "TMT129CD",
        "TMT130N",
        "TMT130C",
        "TMT130ND",
        "TMT130CD",
        "TMT131N",
        "TMT131C",
        "TMT131ND",
        "TMT131CD",
        "TMT132N",
        "TMT132C",
        "TMT132ND",
        "TMT132CD",
        "TMT133N",
        "TMT133C",
        "TMT133ND",
        "TMT133CD",
        "TMT134N",
        "TMT134ND",
        "TMT134CD",
        "TMT135ND",
    ),
    "tmt35plex": (
        "TMT126",
        "TMT127N",
        "TMT127C",
        "TMT127D",
        "TMT128N",
        "TMT128C",
        "TMT128ND",
        "TMT128CD",
        "TMT129N",
        "TMT129C",
        "TMT129ND",
        "TMT129CD",
        "TMT130N",
        "TMT130C",
        "TMT130ND",
        "TMT130CD",
        "TMT131N",
        "TMT131C",
        "TMT131ND",
        "TMT131CD",
        "TMT132N",
        "TMT132C",
        "TMT132ND",
        "TMT132CD",
        "TMT133N",
        "TMT133C",
        "TMT133ND",
        "TMT133CD",
        "TMT134N",
        "TMT134C",
        "TMT134ND",
        "TMT134CD",
        "TMT135N",
        "TMT135ND",
        "TMT135CD",
    ),
    "itraq4plex": ("ITRAQ114", "ITRAQ115", "ITRAQ116", "ITRAQ117"),
    "itraq8plex": (
        "ITRAQ113",
        "ITRAQ114",
        "ITRAQ115",
        "ITRAQ116",
        "ITRAQ117",
        "ITRAQ118",
        "ITRAQ119",
        "ITRAQ121",
    ),
    "silac2plex": ("SILAC light", "SILAC heavy"),
    "silac3plex": ("SILAC light", "SILAC medium", "SILAC heavy"),
    "lfq": ("LFQ",),
}

CHANNEL_MAP: dict[str, dict[int, str]] = {
    plex: dict(enumerate(labels, start=1)) for plex, labels in _CHANNEL_LABELS.items()
}

# Backwards-compatible label -> ordinal lookups used by the OpenMS converter.
TMT_PLEXES: dict[str, dict[str, int]] = {
    plex: {label: ordinal for ordinal, label in channels.items()}
    for plex, channels in CHANNEL_MAP.items()
    if plex.startswith("tmt")
}
ITRAQ_4PLEX: dict[str, int] = {label.lower(): ordinal for ordinal, label in CHANNEL_MAP["itraq4plex"].items()}
ITRAQ_8PLEX: dict[str, int] = {label.lower(): ordinal for ordinal, label in CHANNEL_MAP["itraq8plex"].items()}
SILAC_2PLEX: dict[str, int] = {label.lower(): ordinal for ordinal, label in CHANNEL_MAP["silac2plex"].items()}
SILAC_3PLEX: dict[str, int] = {label.lower(): ordinal for ordinal, label in CHANNEL_MAP["silac3plex"].items()}

# OpenMS enzyme name mappings (SDRF names to OpenMS names)
ENZYME_MAPPINGS = {
    "Glutamyl endopeptidase": "glutamyl endopeptidase",
    "Trypsin/p": "Trypsin/P",
    "Trypchymo": "TrypChymo",
    "Lys-c": "Lys-C",
    "Lys-c/p": "Lys-C/P",
    "Lys-n": "Lys-N",
    "Arg-c": "Arg-C",
    "Arg-c/p": "Arg-C/P",
    "Asp-n": "Asp-N",
    "Asp-n/b": "Asp-N/B",
    "Asp-n_ambic": "Asp-N_ambic",
    "Chymotrypsin/p": "Chymotrypsin/P",
    "Cnbr": "CNBr",
    "V8-de": "V8-DE",
    "V8-e": "V8-E",
    "Elastase-trypsin-chymotrypsin": "elastase-trypsin-chymotrypsin",
    "Pepsina": "PepsinA",
    "Unspecific cleavage": "unspecific cleavage",
    "No cleavage": "no cleavage",
}

# Default TMT modifications when not specified in SDRF
TMT_DEFAULT_MODS = {
    "tmt6plex": ["TMT6plex (K)", "TMT6plex (N-term)"],
    "tmt10plex": ["TMT6plex (K)", "TMT6plex (N-term)"],
    "tmt11plex": ["TMT6plex (K)", "TMT6plex (N-term)"],
    "tmt16plex": ["TMTpro (K)", "TMTpro (N-term)"],
    "tmt18plex": ["TMTpro (K)", "TMTpro (N-term)"],
    "tmt32plex": ["TMTpro (K)", "TMTpro (N-term)"],
    "tmt35plex": ["TMTpro (K)", "TMTpro (N-term)"],
}

# Default iTRAQ modifications when not specified in SDRF
ITRAQ_DEFAULT_MODS = {
    "itraq4plex": ["iTRAQ4plex (K)", "iTRAQ4plex (N-term)"],
    "itraq8plex": ["iTRAQ8plex (K)", "iTRAQ8plex (N-term)"],
}
